import React from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { format } from 'date-fns';

interface EwayBillPrintProps {
    sale: any;
    companyInfo: any;
    customerInfo: any;
}

export const EwayBillPrint: React.FC<EwayBillPrintProps> = ({ sale, companyInfo, customerInfo }) => {
    const ewayBillNo = sale.ewayBillNumber || "GENERATED-ON-UPLOAD";
    const docDate = format(new Date(sale.saleDate), "dd/MM/yyyy");

    // Create a string for the QR code containing key info
    const qrValue = `EWB:${ewayBillNo}|Date:${docDate}|GSTIN:${companyInfo.gstNumber}|To:${customerInfo.gstNumber}|Amt:${sale.totalAmount}`;

    return (
        <div className="p-8 bg-white text-black font-sans max-w-[800px] mx-auto border border-gray-300 print:border-0" id="eway-bill-capture">
            <div className="flex justify-between items-start border-b-2 border-black pb-4 mb-6">
                <div>
                    <h1 className="text-2xl font-bold uppercase">E-Way Bill</h1>
                    <p className="text-sm font-semibold">Government of India</p>
                </div>
                <div className="text-right">
                    <QRCodeSVG value={qrValue} size={80} level="M" />
                </div>
            </div>

            <div className="grid grid-cols-2 gap-8 mb-6">
                <div>
                    <h2 className="font-bold border-b border-gray-400 mb-2">E-WAY BILL DETAILS</h2>
                    <div className="text-sm space-y-1">
                        <div className="flex justify-between"><span>E-Way Bill No:</span> <span className="font-bold">{ewayBillNo}</span></div>
                        <div className="flex justify-between"><span>E-Way Bill Date:</span> <span>{docDate}</span></div>
                        <div className="flex justify-between"><span>Generated By:</span> <span>{companyInfo.gstNumber}</span></div>
                        <div className="flex justify-between"><span>Valid From:</span> <span>{docDate} 10:30 AM</span></div>
                        <div className="flex justify-between"><span>Valid Until:</span> <span>{format(new Date(new Date(sale.saleDate).getTime() + 86400000), "dd/MM/yyyy")}</span></div>
                    </div>
                </div>
                <div>
                    <h2 className="font-bold border-b border-gray-400 mb-2">PART - A</h2>
                    <div className="text-sm space-y-1">
                        <div className="flex justify-between"><span>GSTIN of Supplier:</span> <span className="font-bold">{companyInfo.gstNumber}</span></div>
                        <div className="flex justify-between"><span>Place of Dispatch:</span> <span>{companyInfo.address?.split(',')[0]}</span></div>
                        <div className="flex justify-between"><span>GSTIN of Recipient:</span> <span className="font-bold">{customerInfo.gstNumber || "URP"}</span></div>
                        <div className="flex justify-between"><span>Place of Delivery:</span> <span>{customerInfo.address?.split(',')[0]}</span></div>
                        <div className="flex justify-between"><span>Document No:</span> <span className="font-bold">SALE-{sale.id}</span></div>
                        <div className="flex justify-between"><span>Document Date:</span> <span>{docDate}</span></div>
                        <div className="flex justify-between border-t border-gray-200 mt-2 pt-2"><span>Taxable Value:</span> <span>₹{(Number(sale.totalAmount) - (Number(sale.cgstAmount || 0) + Number(sale.sgstAmount || 0) + Number(sale.igstAmount || 0))).toFixed(2)}</span></div>
                        {Number(sale.cgstAmount) > 0 && <div className="flex justify-between text-xs text-gray-600 italic"><span>CGST:</span> <span>₹{Number(sale.cgstAmount).toFixed(2)}</span></div>}
                        {Number(sale.sgstAmount) > 0 && <div className="flex justify-between text-xs text-gray-600 italic"><span>SGST:</span> <span>₹{Number(sale.sgstAmount).toFixed(2)}</span></div>}
                        {Number(sale.igstAmount) > 0 && <div className="flex justify-between text-xs text-gray-600 italic"><span>IGST:</span> <span>₹{Number(sale.igstAmount).toFixed(2)}</span></div>}
                        <div className="flex justify-between border-t border-black mt-1 pt-1"><span className="font-bold">Total Amount:</span> <span className="font-bold">₹{Number(sale.totalAmount).toFixed(2)}</span></div>
                        <div className="flex justify-between"><span>HSN Code:</span> <span>{sale.lineItems?.[0]?.hsnCode || "-"}</span></div>
                        <div className="flex justify-between"><span>Reason for Transportation:</span> <span>Outward - Supply</span></div>
                    </div>
                </div>
            </div>

            <div className="mb-6">
                <h2 className="font-bold border-b border-gray-400 mb-2">PART - B</h2>
                <table className="w-full text-sm border-collapse border border-gray-400">
                    <thead className="bg-gray-100 text-left">
                        <tr>
                            <th className="border border-gray-400 p-2">Mode</th>
                            <th className="border border-gray-400 p-2">Vehicle / Trans Doc No & Date</th>
                            <th className="border border-gray-400 p-2">From</th>
                            <th className="border border-gray-400 p-2">Entered Date</th>
                            <th className="border border-gray-400 p-2">Entered By</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td className="border border-gray-400 p-2">Road</td>
                            <td className="border border-gray-400 p-2 font-bold">{sale.vehicleNumber || "-"}</td>
                            <td className="border border-gray-400 p-2">{companyInfo.address?.split(',')[0]}</td>
                            <td className="border border-gray-400 p-2">{docDate}</td>
                            <td className="border border-gray-400 p-2">{companyInfo.gstNumber}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div className="border-t-2 border-black pt-4 text-[10px] text-gray-500 flex justify-between">
                <span>* This is a computer generated E-Way Bill</span>
                <span>Printed on: {new Date().toLocaleString()}</span>
            </div>

            <div className="mt-8 text-center no-print">
                <button
                    onClick={() => window.print()}
                    className="bg-blue-600 text-white px-4 py-2 rounded shadow hover:bg-blue-700"
                >
                    Print E-Way Bill
                </button>
            </div>
        </div>
    );
};
